services:
  cleversell:
    build: .
    image: cleversell:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.cleversell.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"

      # HTTPS ROUTER
      - "traefik.http.routers.cleversell.rule=Host(\"cleversell.com.ar\") || Host(\"www.cleversell.com.ar\")"
      - "traefik.http.routers.cleversell.entrypoints=websecure"
      - "traefik.http.routers.cleversell.tls=true"
      - "traefik.http.routers.cleversell.middlewares=default-sec-headers@file,gzip-compress@file,cors-headers@file"

      # HTTP ROUTER â†’ redirect a HTTPS
      - "traefik.http.routers.cleversell-http.rule=Host(\"cleversell.com.ar\") || Host(\"www.cleversell.com.ar\")"
      - "traefik.http.routers.cleversell-http.entrypoints=web"
      - "traefik.http.routers.cleversell-http.middlewares=redirect-https@file"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik_proxy
